server:
  port: 8083

spring:
  application:
    name: vpn-conf

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/vpnconfigsdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

vps:
  host: ${VPS_HOST:80.76.34.9}
  user: ${VPS_USER:root}
  port: ${VPS_PORT:22}
  key-path: ${VPS_KEY_PATH:/home/alexandr/.ssh/shade_vpn}
  xray-config: ${VPS_XRAY_CONFIG:/usr/local/etc/xray/config.json}
  xray-port: ${VPS_XRAY_PORT:443}
  public-key: ${VPS_PUBLIC_KEY:5nPsHtj4eD4Qd2pdjx9Wp_laWWHDcD50F8Jq8i97gno}
  short-id: ${VPS_SHORT_ID:}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.vpn.vpn_conf: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG
    org.telegram: DEBUG
    OkHttp3: DEBUG